import { Provider, ChatMessage } from "./base.js";
import { searchPiyao, hasDirectMatch } from "../knowledge-base.js";

// 轻量级规则引擎：基于关键词和模式识别常见针对老人的虚假信息
// 不依赖任何大模型，零配置即可使用
// 现在会先查询本地辟谣知识库，再回落到硬编码规则

/**
 * 从truth文本中提取与指定claim最相关的段落。
 * 合集文章的truth可能包含多条谣言，需要找到对应的那一段。
 */
function extractRelevantTruth(truth: string, claim: string): string {
  if (!truth) return "";
  // 按换行分割成段落
  const paragraphs = truth.split(/\n+/).filter(p => p.trim().length > 0);
  if (paragraphs.length === 0) return truth.slice(0, 150);

  const claimLower = claim.toLowerCase();
  // 优先找包含claim关键词的段落
  for (const p of paragraphs) {
    const pLower = p.toLowerCase();
    // 提取claim中的3-gram进行匹配
    const claim3grams: string[] = [];
    for (let i = 0; i <= claimLower.length - 3; i++) {
      claim3grams.push(claimLower.slice(i, i + 3));
    }
    const hits = claim3grams.filter(g => pLower.includes(g)).length;
    if (hits >= 2 || pLower.includes(claimLower.slice(0, 6))) {
      return p.trim();
    }
  }
  // 没有找到匹配段落，返回第一个非空段落
  return paragraphs[0].trim();
}

interface Rule {
  id: string;
  patterns: RegExp[];
  score: number;
  verdict: "safe" | "misinformation" | "scam" | "suspicious" | "needs-verification";
  redFlagZh: string;
  redFlagEn: string;
  elderZh: string;
  elderEn: string;
  actionZh: string;
  actionEn: string;
  summaryZh: string;
  summaryEn: string;
}

// ── 通用诈骗/谣言规则（高优先级，分数低=更危险）─────────────────────

const SCAM_RULES: Rule[] = [
  {
    id: "lottery-scam",
    patterns: [/恭喜发财.*领取/, /中奖.*点击/, /红包.*领取/, /免费.*抽奖/, /幸运用户/],
    score: 5,
    verdict: "scam",
    redFlagZh: "天上不会掉馅饼，要求先点击、先付款、先填信息的多为诈骗",
    redFlagEn: "There's no free lunch. Requests to click, pay, or fill in information first are usually scams.",
    elderZh: "无缘无故中奖都是骗人的。点进去可能被骗钱，或者手机中病毒。",
    elderEn: "Winning a prize out of nowhere is always a scam. Clicking may steal money or infect the phone.",
    actionZh: "立即删除此类消息，不要点击任何链接，必要时报警。",
    actionEn: "Delete such messages immediately, don't click any links, and call the police if necessary.",
    summaryZh: "典型的中奖诈骗或钓鱼链接，目标是骗取钱财或个人信息。",
    summaryEn: "A typical prize scam or phishing link aiming to steal money or personal information.",
  },
  {
    id: "urgency-threat",
    patterns: [/紧急通知/, /速看.*删除/, /马上.*来不及了/, /最后.*小时/, /国家.*秘密/],
    score: 20,
    verdict: "scam",
    redFlagZh: "制造紧迫感和恐惧，是诈骗和谣言的常见开场白",
    redFlagEn: "Creates urgency and fear — a common opening for scams and hoaxes.",
    elderZh: "真正重要的通知不会用'速看马上要删'这种吓唬人的话。别点里面的链接。",
    elderEn: "Real important announcements don't use scary phrases like 'watch before deletion.' Don't click any links.",
    actionZh: "务必检查信息来源，不要点击不明链接，更不要填写个人信息或转账。",
    actionEn: "Always check the source, don't click unknown links, and never share personal info or transfer money.",
    summaryZh: "通过紧迫感和恐惧心理诱导用户快速行动，常伴随钓鱼链接或诈骗。",
    summaryEn: "Induces quick action through urgency and fear, often accompanied by phishing links or fraud.",
  },
  {
    id: "government-deception",
    patterns: [/国家.*政策/, /政府.*补贴/, /社保.*更新/, /医保.*停用/, /养老金.*调整/],
    score: 15,
    verdict: "scam",
    redFlagZh: "冒充政府部门或官方政策，要求点击链接或提供个人信息",
    redFlagEn: "Impersonates government departments or official policies, demanding clicks or personal info.",
    elderZh: "政府发通知会打电话或上门的，不会发一个链接让你点。千万别填身份证和银行卡。",
    elderEn: "The government calls or visits for official notices, not via random links. Never enter ID or bank card info.",
    actionZh: "通过政府官网（.gov.cn）或拨打 12345 市民热线核实。",
    actionEn: "Verify through official government websites (.gov.cn) or the 12345 hotline.",
    summaryZh: "冒充政府机构进行诈骗，老年人是重点受害群体。",
    summaryEn: "Impersonates government agencies to scam people, with elders as the primary victims.",
  },
  {
    id: "fee-first-scam",
    patterns: [/先交.*手续费/, /先.*税费.*领奖/, /保证金.*退还/, /解冻.*资金/],
    score: 5,
    verdict: "scam",
    redFlagZh: "任何要求先交钱才能领奖/退款的都是诈骗",
    redFlagEn: "Any request to pay upfront to claim a prize or refund is a scam.",
    elderZh: "真正中奖不会让您先交钱的。先让交钱的，百分百是骗子。",
    elderEn: "Real prizes never require upfront payment. If they ask for money first, it's 100% a scam.",
    actionZh: "立即停止联系，不要转账，向子女或警方求助。",
    actionEn: "Stop all contact immediately, do not transfer money, ask family or police for help.",
    summaryZh: "经典的先付费诈骗套路，常见于中奖、退款、解冻资金等场景。",
    summaryEn: "Classic pay-first scam, common in prize claims, refunds, and fund unfreezing.",
  },
  {
    id: "investment-scam",
    patterns: [/内幕.*股票/, /保本.*高收益/, /年化.*1[0-9]%/, /稳赚.*不赔/, /数字货币.*抄底/],
    score: 5,
    verdict: "scam",
    redFlagZh: "承诺高收益、零风险的投资都是骗局",
    redFlagEn: "Any investment promising high returns with zero risk is a scam.",
    elderZh: "钱生钱哪有那么容易。说稳赚不赔的，都是想骗您的本金。",
    elderEn: "Making money isn't that easy. Anyone promising guaranteed returns wants to steal your principal.",
    actionZh: "不轻信高息理财，投资需通过正规持牌机构。",
    actionEn: "Don't trust high-interest schemes; invest only through licensed institutions.",
    summaryZh: "典型的投资诈骗，利用高收益承诺诱骗老年人投入资金。",
    summaryEn: "Typical investment fraud using high-return promises to lure elderly victims.",
  },
  {
    id: "express-scam",
    patterns: [/快递.*到达.*链接/, /快递.*异常.*点击/, /包裹.*确认.*地址/],
    score: 10,
    verdict: "scam",
    redFlagZh: "冒充快递公司发送钓鱼链接，窃取个人信息",
    redFlagEn: "Impersonates courier companies to send phishing links and steal personal information.",
    elderZh: "快递公司不会发短信让您点链接。要点也是去官方APP查。",
    elderEn: "Courier companies won't text you links to click. Check the official app instead.",
    actionZh: "不要点击短信中的链接，通过官方快递APP或客服核实。",
    actionEn: "Don't click links in SMS messages; verify through official courier apps or customer service.",
    summaryZh: "冒充快递公司的钓鱼诈骗，目标是获取个人信息或植入木马。",
    summaryEn: "Phishing scam impersonating courier companies to obtain personal info or install malware.",
  },
];

// ── 健康养生谣言规则 ────────────────────────────────────────────

const HEALTH_RULES: Rule[] = [
  {
    id: "soften-blood-vessels",
    patterns: [/软化血管/, /喝醋.*血管/, /血管.*硬化.*(吃|喝)/, /清理血管/],
    score: 15,
    verdict: "misinformation",
    redFlagZh: '"软化血管"不是医学概念，动脉粥样硬化不可逆',
    redFlagEn: '"Softening blood vessels" is not a medical concept; atherosclerosis is irreversible.',
    elderZh: "血管变硬就像水管老化，喝醋洗不干净，喝多了反而伤胃。医院大夫没这么说过。",
    elderEn: "Hardened blood vessels are like aging pipes; vinegar won't clean them, and too much can hurt your stomach. Doctors don't say this.",
    actionZh: "提醒老人不要相信此类养生偏方，如有血管问题应去医院就诊。",
    actionEn: "Remind the elder not to believe such folk remedies. Go to the hospital for real vascular issues.",
    summaryZh: "典型的健康养生谣言，利用老年人对心血管疾病的恐惧进行传播，没有科学依据。",
    summaryEn: "A typical health hoax exploiting elderly fear of cardiovascular disease, with no scientific basis.",
  },
  {
    id: "acid-base-constitution",
    patterns: [/酸碱体质/, /酸性体质.*癌/, /碱性食物.*防癌/, /体质偏酸/],
    score: 10,
    verdict: "misinformation",
    redFlagZh: '"酸碱体质"理论已被医学界否定，创始人曾在美国被判罚',
    redFlagEn: '"Acid-base constitution" theory has been debunked; its founder was fined in the US.',
    elderZh: "人的身体不会分成酸性和碱性，吃什么都改变不了。这是骗人的说法。",
    elderEn: "The human body doesn't divide into acidic and alkaline types. Food can't change that. This is a scam.",
    actionZh: "如果老人已购买相关保健品，建议保留证据并向市场监管部门举报。",
    actionEn: "If the elder bought related health products, keep evidence and report to consumer protection authorities.",
    summaryZh: "已被辟谣多年的伪科学理论，常被用于推销保健品和特殊食品。",
    summaryEn: "A long-debunked pseudoscience often used to sell health products and special foods.",
  },
  {
    id: "red-wine-heart",
    patterns: [/红酒.*软化血管/, /红酒.*预防.*心脏病/, /睡前.*红酒.*延年益寿/],
    score: 15,
    verdict: "misinformation",
    redFlagZh: "少量饮酒有益心脏的说法已被WHO否定，任何饮酒都有害",
    redFlagEn: "WHO has debunked the claim that moderate drinking benefits the heart; any alcohol is harmful.",
    elderZh: "喝酒对心脏没有好处，喝多还伤肝。大夫现在都不建议老人喝酒了。",
    elderEn: "Alcohol doesn't benefit the heart and harms the liver. Doctors no longer recommend drinking for elders.",
    actionZh: "建议老人戒酒或少饮酒，通过健康饮食和运动保护心脏。",
    actionEn: "Suggest the elder quit or reduce drinking; protect the heart through healthy diet and exercise.",
    summaryZh: "已被医学界否定的饮酒有益论，任何剂量的酒精都对健康有害。",
    summaryEn: "A debunked theory that alcohol is beneficial; any amount of alcohol is harmful to health.",
  },
  {
    id: "cancer-food",
    patterns: [/(吃|不吃).*癌/, /(食物|蔬菜|水果).*致癌/, /致癌.*名单/, /千万别吃/],
    score: 25,
    verdict: "misinformation",
    redFlagZh: "将单一食物与癌症直接挂钩，忽略了剂量、个体差异和整体饮食结构",
    redFlagEn: "Directly links a single food to cancer, ignoring dosage, individual differences, and overall diet.",
    elderZh: "没有哪一种食物吃了就一定得癌，也没有哪一种吃了就一定防癌。均衡饮食最重要。",
    elderEn: "No single food guarantees cancer, and no single food prevents it. A balanced diet is what matters.",
    actionZh: "如有饮食健康疑虑，建议咨询正规医院营养科，不要轻信网络榜单。",
    actionEn: "For dietary concerns, consult a hospital nutritionist instead of online lists.",
    summaryZh: "夸大单一食物的致癌或防癌效果，属于伪科学饮食谣言。",
    summaryEn: "Exaggerates the cancer-causing or cancer-preventing effects of a single food, pseudoscience.",
  },
  {
    id: "overnight-cancer",
    patterns: [/隔夜菜.*致癌/, /隔夜.*亚硝酸盐/, /剩菜.*不能.*吃/],
    score: 25,
    verdict: "misinformation",
    redFlagZh: "隔夜菜亚硝酸盐含量远低于安全标准，正常保存食用是安全的",
    redFlagEn: "Nitrite levels in overnight dishes are far below safety standards; properly stored leftovers are safe.",
    elderZh: "剩菜放冰箱盖好，第二天热透了吃没问题。别浪费粮食。",
    elderEn: "Leftovers stored in the fridge and reheated thoroughly are fine. Don't waste food.",
    actionZh: "教导老人正确保存剩菜的方法，不必过度恐慌。",
    actionEn: "Teach the elder proper leftover storage methods; no need for excessive panic.",
    summaryZh: "夸大隔夜菜的亚硝酸盐风险，属于制造不必要恐慌的伪科学。",
    summaryEn: "Exaggerates nitrite risks of overnight dishes, creating unnecessary panic through pseudoscience.",
  },
  {
    id: "microwave-danger",
    patterns: [/微波炉.*致癌/, /微波炉.*辐射/, /微波炉.*破坏.*营养/],
    score: 20,
    verdict: "misinformation",
    redFlagZh: "微波炉加热是安全的物理过程，不会产生致癌物或残留辐射",
    redFlagEn: "Microwave heating is a safe physical process that doesn't produce carcinogens or residual radiation.",
    elderZh: "微波炉加热饭菜又快又安全，不用担心辐射。别信这些吓唬人的话。",
    elderEn: "Microwaving food is fast and safe; don't worry about radiation. Don't believe these scare tactics.",
    actionZh: "向老人解释微波炉的工作原理，消除不必要的恐惧。",
    actionEn: "Explain how microwaves work to the elder to eliminate unnecessary fear.",
    summaryZh: "关于微波炉的谣言已被多次辟谣，属于典型的伪科学恐慌。",
    summaryEn: "Microwave myths have been repeatedly debunked; typical pseudoscientific panic.",
  },
  {
    id: "magnet-therapy",
    patterns: [/磁.*吸走.*毒素/, /磁疗.*治病/, /磁铁.*排毒/, /磁石.*保健/],
    score: 10,
    verdict: "misinformation",
    redFlagZh: "磁场无法吸附或清除人体内的任何毒素，磁疗产品没有医学依据",
    redFlagEn: "Magnetic fields cannot adsorb or remove toxins from the body; magnet therapy has no medical basis.",
    elderZh: "磁铁只能吸铁，吸不走身体里的东西。买这些磁疗产品就是浪费钱。",
    elderEn: "Magnets only attract iron, not things inside your body. Buying magnet therapy products is a waste of money.",
    actionZh: "提醒老人不要购买磁疗床垫、磁疗手环等伪科学产品。",
    actionEn: "Remind the elder not to buy pseudoscientific products like magnetic mattresses or bracelets.",
    summaryZh: "磁疗排毒是完全没有科学依据的伪科学，常见于保健品推销。",
    summaryEn: "Magnet therapy detox has zero scientific basis, commonly used in health product scams.",
  },
  {
    id: "bloodletting-cure",
    patterns: [/放血.*治愈/, /放血.*高血压/, /放血.*疗法/],
    score: 5,
    verdict: "misinformation",
    redFlagZh: "放血疗法是已被淘汰的古代医学手段，不能治愈任何现代疾病",
    redFlagEn: "Bloodletting is an obsolete ancient medical practice that cannot cure any modern disease.",
    elderZh: "放血是老辈子落后的做法，现在医院早就不用了。千万别让人随便放血。",
    elderEn: "Bloodletting is an outdated practice that modern hospitals abandoned long ago. Never let anyone do it.",
    actionZh: "立即制止任何非医疗机构的放血行为，必要时报警。",
    actionEn: "Immediately stop any bloodletting by non-medical institutions; call police if necessary.",
    summaryZh: "放血疗法属于已被现代医学淘汰的危险伪科学，可能危及生命。",
    summaryEn: "Bloodletting is a dangerous, obsolete pseudoscience that may endanger life.",
  },
  {
    id: "raw-loach-detox",
    patterns: [/生泥鳅.*清除.*寄生虫/, /生泥鳅.*排毒/, /吃.*泥鳅.*治病/],
    score: 5,
    verdict: "misinformation",
    redFlagZh: "生泥鳅含有大量寄生虫和致病菌，食用会导致严重感染",
    redFlagEn: "Raw loaches contain numerous parasites and pathogens; eating them causes severe infection.",
    elderZh: "生泥鳅里有虫子，吃了会生病。东西要煮熟了吃。",
    elderEn: "Raw loaches have worms inside; eating them makes you sick. Food must be cooked thoroughly.",
    actionZh: "如老人已食用生泥鳅，建议尽快就医检查寄生虫。",
    actionEn: "If the elder has eaten raw loaches, seek medical examination for parasites immediately.",
    summaryZh: "食用生泥鳅不仅不能排毒，还会导致寄生虫感染，极其危险。",
    summaryEn: "Eating raw loaches cannot detoxify and causes parasitic infections; extremely dangerous.",
  },
  {
    id: "bleach-cure",
    patterns: [/喝漂白水.*治病/, /喝漂白水.*新冠/, /漂白水.*治疗/],
    score: 5,
    verdict: "misinformation",
    redFlagZh: "漂白水是剧毒化学品，饮用会导致器官衰竭甚至死亡",
    redFlagEn: "Bleach is a toxic chemical; drinking it causes organ failure and death.",
    elderZh: "漂白水是洗东西的毒药，喝了会死人的。千万别喝！",
    elderEn: "Bleach is poisonous cleaning chemical. Drinking it can kill you. Never drink it!",
    actionZh: "立即制止，如已误食马上送医洗胃。",
    actionEn: "Stop immediately; if ingested, go to hospital for gastric lavage right away.",
    summaryZh: "饮用漂白水是极其危险的行为，可能导致致命后果。",
    summaryEn: "Drinking bleach is extremely dangerous and may result in fatal consequences.",
  },
  {
    id: "stool-toxin",
    patterns: [/宿便.*排毒/, /宿便.*中毒/, /体内.*6.*公斤.*宿便/],
    score: 10,
    verdict: "misinformation",
    redFlagZh: '"宿便"不是医学概念，肠道没有所谓的毒素需要排出',
    redFlagEn: '"Residual stool" is not a medical concept; the gut has no so-called toxins to expel.',
    elderZh: "肠子里面没有几斤屎憋着。正常上厕所就行，别乱吃泻药。",
    elderEn: "There's no pounds of stool stuck in the gut. Just go to the toilet normally; don't take laxatives randomly.",
    actionZh: "提醒老人不要购买排毒茶、清肠产品，有便秘问题去医院。",
    actionEn: "Remind the elder not to buy detox teas or colon cleanse products; see a doctor for constipation.",
    summaryZh: "宿便排毒是伪科学概念，常用于推销泻药和减肥产品。",
    summaryEn: "Residual stool detox is pseudoscience commonly used to sell laxatives and weight-loss products.",
  },
  {
    id: "lymph-detox",
    patterns: [/淋巴.*排毒/, /淋巴.*按摩.*排出.*毒素/],
    score: 15,
    verdict: "misinformation",
    redFlagZh: "淋巴系统没有'毒素'需要按摩排出，不当按摩反而损伤淋巴管",
    redFlagEn: "The lymphatic system has no 'toxins' requiring massage; improper massage damages lymphatic vessels.",
    elderZh: "淋巴是身体里正常的东西，不需要排。乱按反而可能按坏了。",
    elderEn: "Lymph is a normal part of the body and doesn't need draining. Random pressing may damage it.",
    actionZh: "提醒老人不要去美容院做淋巴排毒按摩。",
    actionEn: "Remind the elder not to get lymphatic drainage massages at beauty parlors.",
    summaryZh: "淋巴排毒按摩是伪科学，可能造成身体损伤。",
    summaryEn: "Lymphatic detox massage is pseudoscience and may cause bodily harm.",
  },
  {
    id: "slap-cure",
    patterns: [/拍打.*治愈.*癌/, /拍打.*拉筋.*治愈/, /拍打.*百病/],
    score: 10,
    verdict: "misinformation",
    redFlagZh: "拍打拉筋不能治愈任何疾病，暴力拍打可能造成皮下出血和组织损伤",
    redFlagEn: "Slapping and tendon-stretching cannot cure any disease; violent slapping causes bruising and tissue damage.",
    elderZh: "拍拍打打治不好病，拍重了还会把血管拍破。有病要去医院。",
    elderEn: "Slapping cannot cure illness, and heavy slapping can burst blood vessels. Go to the hospital when sick.",
    actionZh: "制止老人参加拍打拉筋培训，有疾病及时就医。",
    actionEn: "Stop the elder from attending slap-and-stretch training; seek medical care for illness promptly.",
    summaryZh: "拍打拉筋治愈疾病是伪科学，可能造成身体伤害。",
    summaryEn: "Claiming slapping and stretching cures disease is pseudoscience that may cause bodily harm.",
  },
  {
    id: "onion-virus",
    patterns: [/洋葱.*吸附.*病毒/, /洋葱.*预防.*流感/, /房间.*放洋葱/],
    score: 15,
    verdict: "misinformation",
    redFlagZh: "洋葱没有任何吸附病毒或杀菌的能力，这是毫无根据的传言",
    redFlagEn: "Onions have no ability to adsorb viruses or kill bacteria; this is a baseless rumor.",
    elderZh: "洋葱就是普通的菜，不能防病。放屋里顶多有点味，没用。",
    elderEn: "Onions are just ordinary vegetables that can't prevent disease. Putting them in the room only makes it smell.",
    actionZh: "告诉老人预防流感要勤洗手、戴口罩，不是靠放洋葱。",
    actionEn: "Tell the elder to prevent flu by washing hands and wearing masks, not by placing onions.",
    summaryZh: "洋葱防病毒是毫无科学依据的民间传言。",
    summaryEn: "Onions preventing viruses is a folk rumor with zero scientific basis.",
  },
  {
    id: "silver-detox",
    patterns: [/银镯子.*变黑.*排毒/, /银饰.*变黑.*身体.*毒/],
    score: 15,
    verdict: "misinformation",
    redFlagZh: "银饰变黑是正常氧化反应，与体内毒素无关",
    redFlagEn: "Silver tarnishing is normal oxidation, unrelated to toxins in the body.",
    elderZh: "银子变黑是空气里的硫让它变色了，不是身体有毒。擦擦就亮了。",
    elderEn: "Silver turns black because sulfur in the air reacts with it, not because of body toxins. Polish it and it shines.",
    actionZh: "向老人解释银饰氧化的化学原理。",
    actionEn: "Explain the chemistry of silver oxidation to the elder.",
    summaryZh: "银饰变黑是氧化反应，与排毒无关。",
    summaryEn: "Silver tarnishing is oxidation, unrelated to detoxification.",
  },
  {
    id: "tiptoe-vessels",
    patterns: [/踮脚尖.*血管.*年轻/, /踮脚尖.*软化.*血管/],
    score: 20,
    verdict: "misinformation",
    redFlagZh: "踮脚尖是普通的运动动作，不能逆转血管老化",
    redFlagEn: "Tiptoeing is ordinary exercise and cannot reverse vascular aging.",
    elderZh: "踮脚尖就是活动活动腿，不能让人年轻。多走走比这个强。",
    elderEn: "Tiptoeing just exercises the legs; it can't make you younger. Walking is better.",
    actionZh: "鼓励老人进行适度有氧运动，如散步、太极拳。",
    actionEn: "Encourage the elder to do moderate aerobic exercise like walking or tai chi.",
    summaryZh: "踮脚尖不能逆转血管老化，适度运动才是健康之道。",
    summaryEn: "Tiptoeing cannot reverse vascular aging; moderate exercise is the healthy choice.",
  },
  {
    id: "ginger-feet",
    patterns: [/生姜.*脚底.*治疗.*感冒/, /生姜.*包.*脚.*感冒/],
    score: 25,
    verdict: "misinformation",
    redFlagZh: "生姜包脚不能治疗感冒，可能引发皮肤过敏",
    redFlagEn: "Ginger foot wraps cannot cure colds and may cause skin allergies.",
    elderZh: "感冒要多喝水多休息，生姜包脚不管用。严重了要吃药。",
    elderEn: "For colds, drink water and rest. Ginger foot wraps don't work. Take medicine if it gets serious.",
    actionZh: "提醒老人感冒及时就医，不要迷信偏方。",
    actionEn: "Remind the elder to see a doctor for colds and not rely on folk remedies.",
    summaryZh: "生姜包脚治感冒是民间偏方，没有医学依据。",
    summaryEn: "Ginger foot wraps for colds are a folk remedy with no medical basis.",
  },
  {
    id: "vaccine-autism",
    patterns: [/疫苗.*有毒/, /疫苗.*自闭症/, /打疫苗.*孩子.*病/],
    score: 5,
    verdict: "misinformation",
    redFlagZh: "疫苗经过严格安全测试，与自闭症无任何关联，该说法已被科学界彻底否定",
    redFlagEn: "Vaccines undergo rigorous safety testing and have no link to autism; this claim is thoroughly debunked.",
    elderZh: "疫苗是保护孩子不生病的，打了不会得自闭症。别听那些吓人的话。",
    elderEn: "Vaccines protect children from disease and don't cause autism. Don't listen to scare tactics.",
    actionZh: "向老人展示国家卫健委的疫苗科普资料，消除恐惧。",
    actionEn: "Show the elder vaccine education materials from the National Health Commission to dispel fear.",
    summaryZh: "疫苗导致自闭症是完全错误的谣言，可能造成严重的公共卫生危害。",
    summaryEn: "Vaccines causing autism is a completely false rumor with serious public health consequences.",
  },
  {
    id: "5g-cancer",
    patterns: [/5G.*辐射.*癌/, /5G.*新冠/, /基站.*辐射.*致癌/],
    score: 10,
    verdict: "misinformation",
    redFlagZh: "5G基站辐射远低于国家安全标准，不会导致癌症或疾病",
    redFlagEn: "5G base station radiation is far below national safety standards and does not cause cancer or disease.",
    elderZh: "5G信号塔辐射很小，比太阳光还安全。不会让人得病。",
    elderEn: "5G tower radiation is very low, safer than sunlight. It won't make people sick.",
    actionZh: "向老人解释5G辐射的科学数据，打消顾虑。",
    actionEn: "Explain 5G radiation scientific data to the elder to alleviate concerns.",
    summaryZh: "5G辐射致癌是完全错误的谣言，没有任何科学依据。",
    summaryEn: "5G radiation causing cancer is a completely false rumor with no scientific basis.",
  },
  {
    id: "flat-earth",
    patterns: [/地球是平的/, /宇航员.*照片.*假/, /登月.*骗局/, /登月.*摄影棚/],
    score: 5,
    verdict: "misinformation",
    redFlagZh: "地球是球体，美国登月是真实的历史事件，有大量科学证据支持",
    redFlagEn: "The Earth is spherical; the US moon landing is a real historical event supported by extensive scientific evidence.",
    elderZh: "地球是圆的，人上过月球是真的。这些老谣言别信了。",
    elderEn: "The Earth is round, and humans really landed on the moon. Don't believe these old rumors.",
    actionZh: "向老人展示登月的视频和科学证据，耐心解释。",
    actionEn: "Show the elder moon landing videos and scientific evidence; explain patiently.",
    summaryZh: "地平说和登月骗局论是完全没有科学依据的阴谋论。",
    summaryEn: "Flat Earth and moon landing hoax theories are conspiracy theories with zero scientific basis.",
  },
  {
    id: "conspiracy-911",
    patterns: [/911.*自导自演/, /911.*美国政府.*策划/],
    score: 10,
    verdict: "misinformation",
    redFlagZh: "911恐怖袭击是基地组织策划的真实恐怖事件，有大量证据证实",
    redFlagEn: "The 9/11 attacks were real terrorist events planned by Al-Qaeda, supported by extensive evidence.",
    elderZh: "911是真的恐怖袭击，死了很多人。别信那些胡说八道。",
    elderEn: "9/11 was a real terrorist attack that killed many people. Don't believe nonsense.",
    actionZh: "耐心向老人解释， conspiracy theories 往往利用情绪制造对立。",
    actionEn: "Explain patiently to the elder that conspiracy theories often exploit emotions to create division.",
    summaryZh: "911阴谋论是完全错误的，已被多项独立调查证伪。",
    summaryEn: "9/11 conspiracy theories are completely false and debunked by multiple independent investigations.",
  },
  {
    id: "lab-leak",
    patterns: [/新冠病毒.*实验室.*制造/, /新冠.*生物武器/, /中国.*制造.*病毒/],
    score: 10,
    verdict: "misinformation",
    redFlagZh: "世界卫生组织已确认新冠病毒来自自然界，实验室制造说是政治谣言",
    redFlagEn: "The WHO has confirmed COVID-19 originated from nature; lab-leak claims are political rumors.",
    elderZh: "病毒不是人造的，是自然产生的。别信那些挑拨离间的说法。",
    elderEn: "The virus is not man-made; it occurred naturally. Don't believe divisive claims.",
    actionZh: "向老人展示WHO的科学结论，避免被政治谣言误导。",
    actionEn: "Show the elder WHO scientific conclusions to avoid political rumor misguidance.",
    summaryZh: "新冠病毒实验室泄漏说已被WHO和多项科学研究否定。",
    summaryEn: "COVID-19 lab leak claims have been rejected by the WHO and multiple scientific studies.",
  },
  {
    id: "bioluo-covid",
    patterns: [/板蓝根.*预防.*非典/, /板蓝根.*预防.*新冠/, /双黄连.*预防.*新冠/, /吸烟.*预防.*新冠/],
    score: 15,
    verdict: "misinformation",
    redFlagZh: "没有任何药物可以预防新冠病毒，疫苗接种才是最有效的防护手段",
    redFlagEn: "No medicine can prevent COVID-19; vaccination is the most effective protection.",
    elderZh: "板蓝根、双黄连不能防新冠。打疫苗、戴口罩才是真管用。",
    elderEn: "Banlangen and Shuanghuanglian cannot prevent COVID-19. Vaccines and masks are what really work.",
    actionZh: "提醒老人通过正规渠道获取防疫信息，不要囤无用的药物。",
    actionEn: "Remind the elder to get epidemic prevention information through official channels; don't hoard useless medicines.",
    summaryZh: "声称某药物可预防新冠是已被辟谣的虚假信息。",
    summaryEn: "Claims that certain medicines prevent COVID-19 are debunked misinformation.",
  },
  {
    id: "salt-radiation",
    patterns: [/抢盐.*防辐射/, /吃盐.*防辐射/, /碘盐.*防辐射/],
    score: 20,
    verdict: "misinformation",
    redFlagZh: "食用碘盐无法防护核辐射，过量摄盐反而危害健康",
    redFlagEn: "Iodized salt cannot protect against nuclear radiation; excessive salt intake harms health.",
    elderZh: "吃盐防不了辐射，吃多了还高血压。别跟风抢盐。",
    elderEn: "Eating salt doesn't prevent radiation, and too much causes high blood pressure. Don't panic-buy salt.",
    actionZh: "如老人已大量囤盐，帮助其理性看待，避免浪费。",
    actionEn: "If the elder has hoarded salt, help them view it rationally to avoid waste.",
    summaryZh: "抢盐防辐射是多次出现的谣言，食用碘盐对核辐射无效。",
    summaryEn: "Salt hoarding for radiation protection is a recurring rumor; iodized salt is ineffective against nuclear radiation.",
  },
  {
    id: "transgenic-cancer",
    patterns: [/转基因.*致癌/, /转基因.*不孕不育/, /转基因.*有害/],
    score: 20,
    verdict: "misinformation",
    redFlagZh: "经过批准的转基因食品是安全的，目前没有证据表明其致癌或导致不孕",
    redFlagEn: "Approved GMO foods are safe; there is no evidence they cause cancer or infertility.",
    elderZh: "国家批准的转基因食品是安全的，可以吃。别听那些没根据的吓人的话。",
    elderEn: "GMO foods approved by the state are safe to eat. Don't listen to unfounded scare tactics.",
    actionZh: "向老人展示国家农业农村部关于转基因食品的安全评估报告。",
    actionEn: "Show the elder safety assessment reports on GMO foods from the Ministry of Agriculture.",
    summaryZh: "转基因食品致癌是不实信息，经过科学评估的转基因食品是安全的。",
    summaryEn: "GMO foods causing cancer is false information; scientifically evaluated GMO foods are safe.",
  },
  {
    id: "MSG-danger",
    patterns: [/味精.*化学合成/, /味精.*致癌/, /味精.*掉头发/, /味精.*变笨/],
    score: 25,
    verdict: "misinformation",
    redFlagZh: "味精（谷氨酸钠）是安全的食品增鲜剂，国际食品添加剂委员会认定其安全",
    redFlagEn: "MSG (sodium glutamate) is a safe food flavor enhancer; JECFA certifies its safety.",
    elderZh: "味精是安全的，吃了不会致癌掉头发。做菜少放点就行，别害怕。",
    elderEn: "MSG is safe; it doesn't cause cancer or hair loss. Just use less in cooking; don't be afraid.",
    actionZh: "向老人展示国家食品安全标准关于味精的安全性说明。",
    actionEn: "Show the elder national food safety standards on MSG safety.",
    summaryZh: "味精有害论是已被辟谣的谣言，适量使用完全安全。",
    summaryEn: "MSG danger claims are debunked rumors; moderate use is completely safe.",
  },
  {
    id: "food-taboo",
    patterns: [/食物相克/],
    score: 20,
    verdict: "misinformation",
    redFlagZh: "所谓'食物相克'没有科学依据，中国营养学会已多次辟谣",
    redFlagEn: "So-called 'food incompatibility' has no scientific basis; the Chinese Nutrition Society has repeatedly debunked it.",
    elderZh: "食物相克是假的，正常吃饭不会中毒。荤素搭配、营养均衡就好。",
    elderEn: "Food incompatibility is false. Normal meals won't poison you. Just eat a balanced diet.",
    actionZh: "告诉老人不必被食物相克表束缚，均衡饮食最重要。",
    actionEn: "Tell the elder not to be constrained by food incompatibility charts; a balanced diet is what matters.",
    summaryZh: "食物相克是流传多年的伪科学，已被营养学界否定。",
    summaryEn: "Food incompatibility is long-standing pseudoscience debunked by nutrition science.",
  },
  {
    id: "kelp-radiation",
    patterns: [/海带.*防.*核辐射/, /吃.*海带.*辐射/],
    score: 20,
    verdict: "misinformation",
    redFlagZh: "海带含碘量有限，无法防护核辐射，大量食用反而可能导致碘过量",
    redFlagEn: "Kelp's iodine content is limited and cannot protect against nuclear radiation; excessive consumption may cause iodine overload.",
    elderZh: "吃海带防不了核辐射，吃多了还不好。别信这些吓唬人的话。",
    elderEn: "Eating kelp doesn't prevent nuclear radiation, and too much is bad. Don't believe these scare tactics.",
    actionZh: "提醒老人核辐射防护需听从政府和专业机构的指导。",
    actionEn: "Remind the elder to follow government and professional guidance for radiation protection.",
    summaryZh: "海带防核辐射是完全错误的说法，没有科学依据。",
    summaryEn: "Kelp preventing nuclear radiation is completely false; no scientific basis.",
  },
  {
    id: "brown-sugar-period",
    patterns: [/红糖水.*痛经/, /红糖.*止痛.*痛经/],
    score: 25,
    verdict: "misinformation",
    redFlagZh: "红糖水缓解痛经的效果主要是安慰剂效应，远不如止痛药有效",
    redFlagEn: "Brown sugar water's effect on menstrual pain is mainly placebo; far less effective than painkillers.",
    elderZh: "红糖水喝下去暖和，但真疼起来不如吃止痛药。别硬扛着。",
    elderEn: "Brown sugar water feels warm, but for real pain, painkillers work better. Don't tough it out.",
    actionZh: "建议痛经严重时使用正规止痛药，红糖水可作为辅助。",
    actionEn: "Suggest using proper painkillers for severe menstrual pain; brown sugar water can be supplementary.",
    summaryZh: "红糖水止痛效果有限，不能替代正规药物治疗。",
    summaryEn: "Brown sugar water has limited pain relief and cannot replace proper medication.",
  },
  {
    id: "shake-baby",
    patterns: [/摇晃.*婴儿.*脑瘫/, /摇晃.*婴儿.*治疗/],
    score: 5,
    verdict: "misinformation",
    redFlagZh: "摇晃婴儿极其危险，可能导致摇晃婴儿综合征，严重可致死",
    redFlagEn: "Shaking babies is extremely dangerous and can cause shaken baby syndrome, potentially fatal.",
    elderZh: "千万不能摇晃小婴儿！晃坏了脑子是一辈子的事。",
    elderEn: "Never shake a baby! It can cause permanent brain damage.",
    actionZh: "如看到此类信息，立即提醒家人和朋友绝对不要尝试。",
    actionEn: "If you see such information, immediately remind family and friends never to try it.",
    summaryZh: "摇晃婴儿治疗疾病是极其危险的错误信息，可能造成严重后果。",
    summaryEn: "Shaking babies to treat illness is extremely dangerous misinformation with serious consequences.",
  },
  {
    id: "teletubbies-brainwash",
    patterns: [/天线宝宝.*洗脑/],
    score: 10,
    verdict: "misinformation",
    redFlagZh: "这是毫无根据的阴谋论，儿童动画片经过内容审查，不存在洗脑内容",
    redFlagEn: "This is a baseless conspiracy theory; children's cartoons are content-reviewed and contain no brainwashing.",
    elderZh: "天线宝宝就是普通的动画片，孩子看看没事。别信这些瞎话。",
    elderEn: "Teletubbies is just an ordinary cartoon; it's fine for kids. Don't believe this nonsense.",
    actionZh: "帮助老人辨别网络谣言，不要传播无根据的阴谋论。",
    actionEn: "Help the elder distinguish online rumors; don't spread unfounded conspiracy theories.",
    summaryZh: "天线宝宝洗脑论是毫无根据的阴谋论，属于网络谣言。",
    summaryEn: "Teletubbies brainwashing claims are baseless conspiracy theories and online rumors.",
  },
  {
    id: "moon-aliens",
    patterns: [/月球背面.*外星人/, /月球.*外星人.*基地/],
    score: 10,
    verdict: "misinformation",
    redFlagZh: "中国嫦娥探月工程已拍摄月球背面高清照片，没有任何外星基地",
    redFlagEn: "China's Chang'e lunar missions have photographed the far side of the moon; there are no alien bases.",
    elderZh: "月球背面国家早就拍清楚了，没有什么外星人。别信这些瞎编的故事。",
    elderEn: "The far side of the moon has been clearly photographed; there are no aliens. Don't believe made-up stories.",
    actionZh: "向老人展示中国探月工程的官方科普资料。",
    actionEn: "Show the elder official science popularization materials from China's lunar exploration program.",
    summaryZh: "月球背面有外星人基地是科幻编造，没有任何科学依据。",
    summaryEn: "Alien bases on the far side of the moon are science fiction with no scientific basis.",
  },
  {
    id: "aids-conspiracy",
    patterns: [/艾滋病.*美国.*制造/, /艾滋病.*军方/, /艾滋病.*种族灭绝/],
    score: 10,
    verdict: "misinformation",
    redFlagZh: "艾滋病由HIV病毒引起，起源与野生动物有关，绝非人为制造",
    redFlagEn: "AIDS is caused by the HIV virus, originating from wild animals; it is not man-made.",
    elderZh: "艾滋病是病毒引起的，不是人造的。别信那些阴谋论。",
    elderEn: "AIDS is caused by a virus, not man-made. Don't believe conspiracy theories.",
    actionZh: "帮助老人了解艾滋病的科学知识，消除误解和歧视。",
    actionEn: "Help the elder understand the science of AIDS and eliminate misunderstanding and discrimination.",
    summaryZh: "艾滋病是人造武器的说法是已被辟谣的阴谋论。",
    summaryEn: "Claims that AIDS is a man-made weapon are debunked conspiracy theories.",
  },
  {
    id: "raw-eggplant-cure",
    patterns: [/生吃茄子.*治百病/, /茄子.*治百病/, /张悟本.*茄子/],
    score: 10,
    verdict: "misinformation",
    redFlagZh: "生吃茄子不能治病，过量食用生茄子还可能引起身体不适",
    redFlagEn: "Eating raw eggplant cannot cure illness; excessive consumption may cause physical discomfort.",
    elderZh: "茄子要煮熟了吃，生吃不能治病。别听那些所谓的'神医'瞎说。",
    elderEn: "Eggplant should be cooked; eating it raw doesn't cure illness. Don't listen to so-called 'miracle doctors.'",
    actionZh: "提醒老人生病要去正规医院，不要轻信民间偏方和'神医'。",
    actionEn: "Remind the elder to go to regular hospitals when sick; don't trust folk remedies or 'miracle doctors.'",
    summaryZh: "生吃茄子治百病是张悟本等伪养生专家的骗局，已被揭穿。",
    summaryEn: "Raw eggplant curing all diseases is a scam by pseudo-health experts like Zhang Wuben, already exposed.",
  },
];

// ── 常识安全规则（factual 内容识别）─────────────────────────────

const SAFE_RULES: Rule[] = [
  {
    id: "handwashing-prevents-flu",
    patterns: [/勤洗手.*预防.*流感/, /洗手.*预防.*传染/, /洗手.*减少.*感染/],
    score: 95,
    verdict: "safe",
    redFlagZh: "这是经过科学验证的健康常识",
    redFlagEn: "This is scientifically verified health common sense.",
    elderZh: "洗手能洗掉手上的病菌，确实是预防生病的好办法。",
    elderEn: "Washing hands removes germs; it is indeed a good way to prevent illness.",
    actionZh: "鼓励老人养成勤洗手的习惯，尤其是外出回家后。",
    actionEn: "Encourage the elder to wash hands frequently, especially after going out.",
    summaryZh: "勤洗手预防传染病是科学共识，内容真实可信。",
    summaryEn: "Handwashing to prevent infectious disease is scientific consensus; content is true and trustworthy.",
  },
  {
    id: "seatbelt-saves",
    patterns: [/安全带.*保护.*生命/, /安全带.*减少.*伤害/, /戴头盔.*减少.*伤害/],
    score: 95,
    verdict: "safe",
    redFlagZh: "这是交通安全的基本常识，有大量数据支持",
    redFlagEn: "This is basic traffic safety common sense supported by extensive data.",
    elderZh: "系安全带确实能救命，坐车一定要系好。",
    elderEn: "Seat belts do save lives; always buckle up in the car.",
    actionZh: "提醒老人无论是坐前排还是后排，都要系好安全带。",
    actionEn: "Remind the elder to buckle up whether in the front or back seat.",
    summaryZh: "安全带和头盔是有效的交通安全保护措施，内容真实。",
    summaryEn: "Seat belts and helmets are effective traffic safety measures; content is true.",
  },
  {
    id: "vaccine-effective",
    patterns: [/疫苗.*预防.*传染病/, /疫苗接种.*有效/, /打疫苗.*预防/],
    score: 95,
    verdict: "safe",
    redFlagZh: "疫苗是预防传染病最有效、最经济的手段，这是医学共识",
    redFlagEn: "Vaccines are the most effective and economical way to prevent infectious diseases; this is medical consensus.",
    elderZh: "打疫苗能防生病，这是真有用的。按时打疫苗对身体好。",
    elderEn: "Vaccines prevent illness; they really work. Getting vaccinated on time is good for health.",
    actionZh: "提醒老人按时接种疫苗，包括流感疫苗和肺炎疫苗。",
    actionEn: "Remind the elder to get vaccinated on time, including flu and pneumonia vaccines.",
    summaryZh: "疫苗接种是科学有效的疾病预防手段，内容真实可信。",
    summaryEn: "Vaccination is a scientifically effective disease prevention method; content is true and trustworthy.",
  },
  {
    id: "brushing-teeth",
    patterns: [/刷牙.*预防.*龋齿/, /刷牙.*预防.*牙周病/, /定期刷牙/],
    score: 95,
    verdict: "safe",
    redFlagZh: "刷牙是预防口腔疾病的基本措施",
    redFlagEn: "Brushing teeth is a basic measure to prevent oral diseases.",
    elderZh: "每天刷牙能保护牙齿，不容易蛀牙。这是好习惯。",
    elderEn: "Brushing teeth daily protects them from cavities. This is a good habit.",
    actionZh: "鼓励老人每天早晚刷牙，定期检查口腔健康。",
    actionEn: "Encourage the elder to brush morning and evening and have regular dental checkups.",
    summaryZh: "刷牙预防口腔疾病是科学常识，内容真实。",
    summaryEn: "Brushing teeth to prevent oral disease is scientific common sense; content is true.",
  },
  {
    id: "crosswalk-safety",
    patterns: [/过马路.*斑马线/, /遵守.*交通.*规则/, /走斑马线/],
    score: 95,
    verdict: "safe",
    redFlagZh: "遵守交通规则是保护自身安全的基本要求",
    redFlagEn: "Following traffic rules is a basic requirement for personal safety.",
    elderZh: "过马路走斑马线，看红绿灯，这是保护自己。",
    elderEn: "Cross at zebra crossings and watch the traffic lights; this protects you.",
    actionZh: "提醒老人过马路时注意来往车辆，不闯红灯。",
    actionEn: "Remind the elder to watch for traffic when crossing and not to run red lights.",
    summaryZh: "遵守交通规则是正确的安全常识，内容真实。",
    summaryEn: "Following traffic rules is correct safety common sense; content is true.",
  },
  {
    id: "annual-checkup",
    patterns: [/老年人.*每年.*体检/, /定期.*体检.*健康/, /全面体检/],
    score: 95,
    verdict: "safe",
    redFlagZh: "定期体检有助于早期发现疾病，是科学的健康管理方式",
    redFlagEn: "Regular checkups help detect diseases early; it's a scientific health management approach.",
    elderZh: "每年体检能早发现毛病，及时治疗。这是对自己负责。",
    elderEn: "Annual checkups catch problems early for timely treatment. This is being responsible for yourself.",
    actionZh: "帮老人预约年度体检，关注血压、血糖、血脂等指标。",
    actionEn: "Help the elder schedule annual checkups and monitor blood pressure, sugar, and lipids.",
    summaryZh: "定期体检是科学的健康管理方式，内容真实可信。",
    summaryEn: "Regular checkups are a scientific health management method; content is true and trustworthy.",
  },
  {
    id: "mask-flu",
    patterns: [/口罩.*减少.*感染/, /流感.*季节.*口罩/, /外出.*口罩.*预防/],
    score: 95,
    verdict: "safe",
    redFlagZh: "戴口罩是阻断呼吸道传染病传播的有效手段",
    redFlagEn: "Wearing masks is an effective way to block respiratory infectious disease transmission.",
    elderZh: "流感季节戴口罩能防传染，这是有用的。",
    elderEn: "Wearing masks during flu season prevents infection; this is useful.",
    actionZh: "提醒老人在流感高发季节或人群密集场所佩戴口罩。",
    actionEn: "Remind the elder to wear masks during flu season or in crowded places.",
    summaryZh: "佩戴口罩预防呼吸道传染病是科学有效的措施，内容真实。",
    summaryEn: "Wearing masks to prevent respiratory infections is a scientifically effective measure; content is true.",
  },
  {
    id: "sun-vitamin-d",
    patterns: [/晒太阳.*维生素D/, /阳光.*合成.*维生素/],
    score: 95,
    verdict: "safe",
    redFlagZh: "适度晒太阳确实有助于皮肤合成维生素D",
    redFlagEn: "Moderate sun exposure does help the skin synthesize vitamin D.",
    elderZh: "晒晒太阳对身体好，能补钙。但别在大太阳底下晒太久。",
    elderEn: "Sunlight is good for health and helps calcium absorption. But don't stay too long in strong sun.",
    actionZh: "建议老人每天适度晒太阳15-20分钟，注意防晒。",
    actionEn: "Suggest the elder get 15-20 minutes of sun daily, with sun protection.",
    summaryZh: "适度晒太阳有助于维生素D合成，内容真实。",
    summaryEn: "Moderate sun exposure aids vitamin D synthesis; content is true.",
  },
  {
    id: "sleep-health",
    patterns: [/睡眠.*免疫力/, /睡眠不足.*影响.*健康/, /七到八小时.*睡眠/],
    score: 95,
    verdict: "safe",
    redFlagZh: "充足睡眠对健康至关重要，这是医学共识",
    redFlagEn: "Adequate sleep is crucial for health; this is medical consensus.",
    elderZh: "睡够觉对身体好，精神也好。老人也要保证睡眠。",
    elderEn: "Getting enough sleep is good for health and energy. Elders need sleep too.",
    actionZh: "帮助老人建立规律的作息时间，避免熬夜。",
    actionEn: "Help the elder establish regular sleep habits and avoid staying up late.",
    summaryZh: "充足睡眠有益健康，内容真实可信。",
    summaryEn: "Adequate sleep benefits health; content is true and trustworthy.",
  },
  {
    id: "exercise-lowers-bp",
    patterns: [/运动.*降低.*血压/, /运动.*血压.*有益/, /适度.*运动.*血压/],
    score: 95,
    verdict: "safe",
    redFlagZh: "适度运动确实有助于控制血压，这是经过验证的",
    redFlagEn: "Moderate exercise does help control blood pressure; this is verified.",
    elderZh: "每天走动走动对血压有好处，比坐着强多了。",
    elderEn: "Daily walking is good for blood pressure, much better than sitting.",
    actionZh: "鼓励老人每天进行适度有氧运动，如散步、太极。",
    actionEn: "Encourage the elder to do moderate aerobic exercise daily, like walking or tai chi.",
    summaryZh: "适度运动有助于控制血压，内容真实。",
    summaryEn: "Moderate exercise helps control blood pressure; content is true.",
  },
  {
    id: "smoking-harmful",
    patterns: [/吸烟.*有害.*健康/, /吸烟.*肺癌/, /戒烟.*健康/],
    score: 95,
    verdict: "safe",
    redFlagZh: "吸烟有害健康是明确的科学结论，WHO已确认",
    redFlagEn: "Smoking harms health is a definite scientific conclusion confirmed by the WHO.",
    elderZh: "抽烟确实对身体不好，容易得肺病。能少抽就少抽。",
    elderEn: "Smoking is indeed bad for health and causes lung disease. Smoke less if possible.",
    actionZh: "鼓励老人戒烟或减少吸烟，必要时寻求戒烟门诊帮助。",
    actionEn: "Encourage the elder to quit or reduce smoking; seek smoking cessation clinics if needed.",
    summaryZh: "吸烟有害健康是科学共识，内容真实可信。",
    summaryEn: "Smoking harms health is scientific consensus; content is true and trustworthy.",
  },
  {
    id: "gas-leak",
    patterns: [/燃气泄漏.*开窗/, /燃气.*不能.*开关.*电器/, /燃气.*通风/],
    score: 95,
    verdict: "safe",
    redFlagZh: "燃气泄漏时开窗通风、禁绝火源是正确的应急措施",
    redFlagEn: "Opening windows and eliminating ignition sources during gas leaks is correct emergency response.",
    elderZh: "闻到煤气味要先开窗，别开灯别点火。这是保命的常识。",
    elderEn: "If you smell gas, open windows first; don't turn on lights or ignite anything. This is life-saving common sense.",
    actionZh: "定期检查家中燃气设备，教会老人识别燃气泄漏的方法。",
    actionEn: "Regularly check home gas equipment; teach the elder how to recognize gas leaks.",
    summaryZh: "燃气泄漏应急处理方法是正确的安全常识，内容真实。",
    summaryEn: "Gas leak emergency procedures are correct safety common sense; content is true.",
  },
  {
    id: "fire-escape",
    patterns: [/火灾.*湿毛巾/, /火灾.*弯腰.*逃生/, /着火.*捂住.*口鼻/],
    score: 95,
    verdict: "safe",
    redFlagZh: "火灾时用湿毛巾捂住口鼻、低姿逃生是正确的自救方法",
    redFlagEn: "Using wet towels over mouth and nose and escaping low during fires is correct self-rescue.",
    elderZh: "着火的时候用湿毛巾捂着口鼻，弯着腰跑，这样能少吸点烟。",
    elderEn: "During a fire, cover mouth and nose with a wet towel and crawl to avoid smoke inhalation.",
    actionZh: "向老人讲解火灾逃生要点，确保家中备有灭火器和逃生路线。",
    actionEn: "Explain fire escape essentials to the elder; ensure fire extinguishers and escape routes are available.",
    summaryZh: "火灾逃生自救方法是正确的安全常识，内容真实。",
    summaryEn: "Fire escape self-rescue methods are correct safety common sense; content is true.",
  },
  {
    id: "salt-control",
    patterns: [/高血压.*控制.*盐/, /高血压.*少.*盐/, /控盐.*血压/],
    score: 95,
    verdict: "safe",
    redFlagZh: "控制钠盐摄入是高血压管理的重要措施，这是医学共识",
    redFlagEn: "Controlling sodium intake is an important hypertension management measure; this is medical consensus.",
    elderZh: "少吃盐对血压有好处，做菜少放点盐，别吃太咸。",
    elderEn: "Eating less salt is good for blood pressure; use less salt in cooking and avoid overly salty food.",
    actionZh: "帮助老人调整饮食习惯，使用限盐勺，少吃腌制食品。",
    actionEn: "Help the elder adjust eating habits; use salt-limiting spoons and eat fewer pickled foods.",
    summaryZh: "控制盐摄入有助于高血压管理，内容真实。",
    summaryEn: "Controlling salt intake helps manage hypertension; content is true.",
  },
  {
    id: "calcium-osteoporosis",
    patterns: [/骨质疏松.*补钙/, /老年人.*补钙/, /适当.*补钙/],
    score: 95,
    verdict: "safe",
    redFlagZh: "骨质疏松患者适当补钙是医生建议的标准治疗方案",
    redFlagEn: "Appropriate calcium supplementation for osteoporosis is a standard treatment recommended by doctors.",
    elderZh: "骨头松了要补钙，医生都这么说。多喝牛奶，吃点钙片。",
    elderEn: "For weak bones, take calcium as doctors recommend. Drink more milk and take calcium tablets.",
    actionZh: "建议老人定期检查骨密度，按医嘱补钙和维生素D。",
    actionEn: "Suggest the elder have regular bone density checks and take calcium and vitamin D as prescribed.",
    summaryZh: "骨质疏松补钙是科学建议，内容真实可信。",
    summaryEn: "Calcium supplementation for osteoporosis is scientific advice; content is true and trustworthy.",
  },
  {
    id: "leftovers-reheat",
    patterns: [/剩饭.*加热/, /剩菜.*彻底.*加热/, /剩菜.*加热.*食用/],
    score: 95,
    verdict: "safe",
    redFlagZh: "剩菜彻底加热后再食用是食品安全的基本要求",
    redFlagEn: "Reheating leftovers thoroughly before eating is a basic food safety requirement.",
    elderZh: "剩菜热透了吃是安全的，别浪费粮食。",
    elderEn: "Reheated leftovers are safe to eat; don't waste food.",
    actionZh: "提醒老人剩菜放冰箱保存，食用前彻底加热。",
    actionEn: "Remind the elder to refrigerate leftovers and reheat thoroughly before eating.",
    summaryZh: "剩菜彻底加热后食用是食品安全常识，内容真实。",
    summaryEn: "Reheating leftovers thoroughly is food safety common sense; content is true.",
  },
  {
    id: "screen-time-eyes",
    patterns: [/手机.*时间.*眼睛/, /看.*手机.*眼睛.*疲劳/, /长时间.*看手机/],
    score: 95,
    verdict: "safe",
    redFlagZh: "长时间注视电子屏幕确实会导致视疲劳",
    redFlagEn: "Prolonged screen viewing does cause eye fatigue.",
    elderZh: "看手机时间长了眼睛会累，歇歇眼睛有好处。",
    elderEn: "Looking at phones too long tires the eyes; taking breaks is beneficial.",
    actionZh: "建议老人每看20分钟手机就远眺20秒，保护视力。",
    actionEn: "Suggest the elder look into the distance for 20 seconds after every 20 minutes of phone use.",
    summaryZh: "控制屏幕时间保护视力是科学建议，内容真实。",
    summaryEn: "Limiting screen time to protect vision is scientific advice; content is true.",
  },
  {
    id: "diabetes-monitor",
    patterns: [/糖尿病.*监测.*血糖/, /糖尿病.*定期.*血糖/, /血糖.*监测/],
    score: 95,
    verdict: "safe",
    redFlagZh: "糖尿病患者定期监测血糖是标准的疾病管理措施",
    redFlagEn: "Regular blood sugar monitoring is a standard diabetes management measure.",
    elderZh: "得了糖尿病要经常测血糖，这样才能控制好。",
    elderEn: "If you have diabetes, you need to check blood sugar often to keep it under control.",
    actionZh: "帮助老人学会使用血糖仪，建立定期监测的习惯。",
    actionEn: "Help the elder learn to use a glucometer and establish regular monitoring habits.",
    summaryZh: "糖尿病患者监测血糖是科学的健康管理方式，内容真实。",
    summaryEn: "Blood sugar monitoring for diabetics is scientific health management; content is true.",
  },
  {
    id: "drug-expiry",
    patterns: [/药品.*保质期/, /过期.*药.*不能.*服用/, /过期.*药.*不能.*吃/],
    score: 95,
    verdict: "safe",
    redFlagZh: "过期药品可能失效或产生有害物质，不能服用是基本的用药安全常识",
    redFlagEn: "Expired medicines may lose effectiveness or produce harmful substances; not taking them is basic medication safety.",
    elderZh: "药过期了就不能吃了，吃了可能伤身。定期清理家里的药箱。",
    elderEn: "Don't take expired medicine; it may harm your health. Clean out the medicine cabinet regularly.",
    actionZh: "帮助老人定期检查家中药品有效期，过期药品应送至回收点。",
    actionEn: "Help the elder regularly check medicine expiration dates; expired medicines should be sent to collection points.",
    summaryZh: "过期药品不可服用是基本的用药安全常识，内容真实。",
    summaryEn: "Not taking expired medicine is basic medication safety common sense; content is true.",
  },
  {
    id: "beijing-capital",
    patterns: [/北京.*首都/],
    score: 95,
    verdict: "safe",
    redFlagZh: "北京是中华人民共和国的首都，这是基本国情常识",
    redFlagEn: "Beijing is the capital of the People's Republic of China; this is basic national common sense.",
    elderZh: "北京是国家首都，这是大家都知道的事实。",
    elderEn: "Beijing is the nation's capital; this is common knowledge.",
    actionZh: "无需特别操作，这是一个基本事实。",
    actionEn: "No special action needed; this is a basic fact.",
    summaryZh: "北京是中华人民共和国首都是基本事实，内容真实。",
    summaryEn: "Beijing being the capital of China is a basic fact; content is true.",
  },
  {
    id: "emotion-bp",
    patterns: [/情绪.*激动.*血压.*升高/, /血压.*情绪/],
    score: 95,
    verdict: "safe",
    redFlagZh: "情绪波动确实会影响血压，保持心情平和对高血压患者很重要",
    redFlagEn: "Emotional fluctuations do affect blood pressure; staying calm is important for hypertensive patients.",
    elderZh: "生气、激动的时候血压会高，老人要注意别太激动，心平气和对身体好。",
    elderEn: "Blood pressure rises when angry or excited; elders should stay calm for their health.",
    actionZh: "建议老人学习放松技巧，如深呼吸、冥想，避免情绪剧烈波动。",
    actionEn: "Suggest the elder learn relaxation techniques like deep breathing and meditation to avoid emotional extremes.",
    summaryZh: "情绪影响血压是医学常识，内容真实。",
    summaryEn: "Emotions affecting blood pressure is medical common sense; content is true.",
  },
  {
    id: "eat-veggies",
    patterns: [/多吃.*蔬菜.*水果/, /蔬菜.*水果.*维生素/, /蔬菜.*水果.*膳食纤维/],
    score: 95,
    verdict: "safe",
    redFlagZh: "蔬菜水果富含维生素、矿物质和膳食纤维，是均衡饮食的重要组成部分",
    redFlagEn: "Vegetables and fruits are rich in vitamins, minerals, and fiber, important components of a balanced diet.",
    elderZh: "多吃蔬菜水果对身体好，能补充维生素，还能帮助消化。",
    elderEn: "Eating more vegetables and fruits is good for health, supplements vitamins, and aids digestion.",
    actionZh: "鼓励老人每天摄入适量蔬菜水果，保持饮食多样化。",
    actionEn: "Encourage the elder to eat adequate vegetables and fruits daily for dietary diversity.",
    summaryZh: "多吃蔬菜水果有益健康是科学饮食建议，内容真实。",
    summaryEn: "Eating more vegetables and fruits benefits health; this is scientific dietary advice.",
  },
  {
    id: "drink-water-health",
    patterns: [/喝水.*新陈代谢/, /多喝水.*健康/, /喝足够.*水.*身体/],
    score: 95,
    verdict: "safe",
    redFlagZh: "充足饮水对维持正常新陈代谢和身体机能至关重要",
    redFlagEn: "Adequate hydration is crucial for maintaining normal metabolism and bodily functions.",
    elderZh: "每天喝够水对身体好，能帮助身体正常运转。",
    elderEn: "Drinking enough water daily is good for health and helps the body function normally.",
    actionZh: "提醒老人每天饮水1500-2000毫升，少量多次。",
    actionEn: "Remind the elder to drink 1500-2000 ml of water daily, in small amounts frequently.",
    summaryZh: "充足饮水有益健康是科学常识，内容真实。",
    summaryEn: "Adequate water intake benefits health; this is scientific common sense.",
  },
  {
    id: "summer-heat",
    patterns: [/夏天.*多喝水.*中暑/, /高温.*喝水.*中暑/, /预防.*中暑.*喝水/],
    score: 95,
    verdict: "safe",
    redFlagZh: "高温天气多喝水是预防中暑的有效措施",
    redFlagEn: "Drinking more water in hot weather is an effective measure to prevent heat stroke.",
    elderZh: "天热了多喝水，能防中暑。出门也要注意避暑。",
    elderEn: "Drink more water when it's hot to prevent heat stroke. Also avoid the sun when going out.",
    actionZh: "提醒老人高温天气减少外出，注意补水和休息。",
    actionEn: "Remind the elder to minimize going out in hot weather, stay hydrated, and rest.",
    summaryZh: "高温天多喝水防中暑是正确的健康建议，内容真实。",
    summaryEn: "Drinking water to prevent heat stroke in hot weather is correct health advice.",
  },
  {
    id: "cpr-saves",
    patterns: [/心肺复苏.*挽救.*生命/, /心肺复苏.*急救/],
    score: 95,
    verdict: "safe",
    redFlagZh: "心肺复苏术（CPR）是公认的紧急救命技术，可在心脏骤停时挽救生命",
    redFlagEn: "CPR is a recognized emergency life-saving technique that can save lives during cardiac arrest.",
    elderZh: "心肺复苏是救命的法子，学会了关键时候能救人。",
    elderEn: "CPR is a life-saving method; learning it can help save someone in critical moments.",
    actionZh: "建议老人和家属学习基本急救知识，包括心肺复苏术。",
    actionEn: "Suggest the elder and family learn basic first aid, including CPR.",
    summaryZh: "心肺复苏术是科学有效的急救技术，内容真实。",
    summaryEn: "CPR is a scientifically effective emergency technique; content is true.",
  },
  {
    id: "ventilate-fresh",
    patterns: [/开窗通风.*空气.*清新/, /通风.*空气.*新鲜/, /开窗.*空气.*流通/],
    score: 95,
    verdict: "safe",
    redFlagZh: "定期开窗通风可以置换室内空气，减少二氧化碳和污染物浓度",
    redFlagEn: "Regular ventilation replaces indoor air, reducing carbon dioxide and pollutant concentrations.",
    elderZh: "每天开开窗，让空气流通，对身体好。",
    elderEn: "Open windows daily to let air circulate; it's good for health.",
    actionZh: "建议老人每天开窗通风2-3次，每次15-30分钟。",
    actionEn: "Suggest the elder open windows for ventilation 2-3 times daily, 15-30 minutes each time.",
    summaryZh: "定期开窗通风有益健康是科学常识，内容真实。",
    summaryEn: "Regular ventilation benefits health; this is scientific common sense.",
  },
  {
    id: "exercise-better-than-sedentary",
    patterns: [/锻炼.*比.*久坐.*健康/, /久坐.*不健康/, /适度.*运动.*比.*坐着/],
    score: 95,
    verdict: "safe",
    redFlagZh: "世界卫生组织明确指出，久坐是健康风险因素，适度运动有益健康",
    redFlagEn: "The WHO clearly states that sedentary behavior is a health risk factor, and moderate exercise benefits health.",
    elderZh: "多动动比老坐着强，走动走动对身体好。",
    elderEn: "Moving around is better than sitting all day; walking is good for health.",
    actionZh: "鼓励老人减少久坐时间，每隔一小时起身活动。",
    actionEn: "Encourage the elder to reduce sedentary time and get up to move every hour.",
    summaryZh: "适度运动优于久坐是科学共识，内容真实。",
    summaryEn: "Moderate exercise being better than sedentary behavior is scientific consensus; content is true.",
  },
  {
    id: "walk-after-meal",
    patterns: [/饭后.*散步.*消化/, /饭后.*走动.*消化/],
    score: 95,
    verdict: "safe",
    redFlagZh: "饭后适度散步有助于促进胃肠蠕动，帮助消化吸收",
    redFlagEn: "A moderate walk after meals helps promote gastrointestinal motility and aids digestion.",
    elderZh: "吃完饭后慢慢走走，能帮助消化。但别走太快太急。",
    elderEn: "A slow walk after eating helps digestion. But don't walk too fast or strenuously.",
    actionZh: "建议老人饭后休息15-20分钟再进行轻度散步。",
    actionEn: "Suggest the elder rest 15-20 minutes after eating before taking a light walk.",
    summaryZh: "饭后散步有助于消化是科学建议，内容真实。",
    summaryEn: "Walking after meals aids digestion; this is scientific advice.",
  },
];

// ── 夸大内容规则 ──────────────────────────────────────────────

const EXAGGERATED_RULES: Rule[] = [
  {
    id: "garlic-kills-all",
    patterns: [/大蒜.*杀死.*所有.*细菌/, /大蒜.*杀菌.*万能/],
    score: 40,
    verdict: "suspicious",
    redFlagZh: "大蒜有一定的抗菌作用，但不可能杀死所有细菌，更无法替代药物",
    redFlagEn: "Garlic has some antibacterial effects, but cannot kill all bacteria or replace medicine.",
    elderZh: "大蒜是好东西，但不能当药吃。生病了还是要看大夫。",
    elderEn: "Garlic is good, but it's not medicine. See a doctor when sick.",
    actionZh: "提醒老人大蒜不能替代正规医疗。",
    actionEn: "Remind the elder that garlic cannot replace proper medical treatment.",
    summaryZh: "夸大大蒜的抗菌效果，属于常见的夸大宣传。",
    summaryEn: "Exaggerates garlic's antibacterial effects; common exaggerated claims.",
  },
  {
    id: "red-dates-blood",
    patterns: [/红枣.*补血.*特别/, /红枣.*贫血.*多吃/],
    score: 45,
    verdict: "suspicious",
    redFlagZh: "红枣含铁量有限，补血效果不如红肉和动物肝脏",
    redFlagEn: "Red dates contain limited iron; their blood-boosting effect is inferior to red meat and liver.",
    elderZh: "红枣可以吃，但补血主要靠吃肉和肝脏。",
    elderEn: "Red dates are fine, but meat and liver are better for blood health.",
    actionZh: "建议贫血老人通过均衡饮食和医生建议补充铁剂。",
    actionEn: "Suggest anemic elders improve diet and take iron supplements as advised by doctors.",
    summaryZh: "红枣补血效果被夸大，属于常见的饮食夸大宣传。",
    summaryEn: "Red dates' blood-boosting effect is exaggerated; common dietary夸大 claims.",
  },
  {
    id: "ejiao-blood",
    patterns: [/阿胶.*补血.*圣品/, /阿胶.*女人.*一定.*吃/],
    score: 40,
    verdict: "suspicious",
    redFlagZh: "阿胶的补血效果缺乏高质量临床证据，价格昂贵性价比低",
    redFlagEn: "Ejiao's blood-boosting effect lacks high-quality clinical evidence; expensive with low cost-effectiveness.",
    elderZh: "阿胶贵还不一定有用，补血不如吃点好的、睡个好觉。",
    elderEn: "Ejiao is expensive and may not work; better nutrition and sleep help more with blood health.",
    actionZh: "提醒老人理性看待阿胶等滋补品，不要过度消费。",
    actionEn: "Remind the elder to view supplements like ejiao rationally and avoid overspending.",
    summaryZh: "阿胶补血效果被夸大，属于高价低效的滋补品宣传。",
    summaryEn: "Ejiao's blood-boosting effect is exaggerated; expensive, low-efficiency supplement marketing.",
  },
  {
    id: "bone-soup-calcium",
    patterns: [/骨头汤.*补钙.*最好/, /多喝.*骨头汤.*补钙/],
    score: 45,
    verdict: "suspicious",
    redFlagZh: "骨头汤中的钙含量极低，且多为不易吸收的游离钙",
    redFlagEn: "Bone soup contains very little calcium, mostly insoluble free calcium.",
    elderZh: "骨头汤好喝但补钙不行，补钙要喝牛奶吃钙片。",
    elderEn: "Bone soup tastes good but doesn't supplement calcium well; drink milk and take calcium tablets.",
    actionZh: "建议老人通过牛奶、豆制品和钙片补钙。",
    actionEn: "Suggest the elder get calcium from milk, soy products, and calcium tablets.",
    summaryZh: "骨头汤补钙效果被夸大，属于常见的饮食误区。",
    summaryEn: "Bone soup's calcium supplement effect is exaggerated; common dietary misconception.",
  },
  {
    id: "local-eggs-better",
    patterns: [/土鸡蛋.*营养.*高/, /土鸡蛋.*洋鸡蛋/],
    score: 50,
    verdict: "suspicious",
    redFlagZh: "土鸡蛋和洋鸡蛋营养成分基本相同，价格差异主要来自生产方式",
    redFlagEn: "Free-range and farm eggs have basically the same nutrition; price difference comes from production methods.",
    elderZh: "土鸡蛋和超市鸡蛋营养差不多，哪个便宜买哪个。",
    elderEn: "Free-range and supermarket eggs have similar nutrition; buy whichever is cheaper.",
    actionZh: "告诉老人不必刻意追求土鸡蛋，正规渠道购买的鸡蛋都安全。",
    actionEn: "Tell the elder not to deliberately pursue free-range eggs; eggs from正规 channels are all safe.",
    summaryZh: "土鸡蛋营养价值被夸大，与洋鸡蛋差异不大。",
    summaryEn: "Free-range egg nutritional value is exaggerated; not much different from farm eggs.",
  },
  {
    id: "green-bean-cure",
    patterns: [/绿豆汤.*解百毒/, /绿豆汤.*包治百病/],
    score: 20,
    verdict: "misinformation",
    redFlagZh: "绿豆汤是普通饮品，没有任何解毒或包治百病的功效",
    redFlagEn: "Mung bean soup is an ordinary beverage with no detox or cure-all effects.",
    elderZh: "绿豆汤就是普通的汤，不能治病。夏天喝了解暑还行。",
    elderEn: "Mung bean soup is just ordinary soup; it can't cure illness. It's okay for cooling off in summer.",
    actionZh: "提醒老人绿豆汤不能替代药物治疗。",
    actionEn: "Remind the elder that mung bean soup cannot replace drug treatment.",
    summaryZh: "绿豆汤解百毒是完全没有科学依据的谣言。",
    summaryEn: "Mung bean soup detoxifying is a completely baseless rumor.",
  },
  {
    id: "celery-pressure",
    patterns: [/芹菜.*降压.*神菜/, /芹菜.*不用.*吃降压药/],
    score: 35,
    verdict: "misinformation",
    redFlagZh: "芹菜含有一定降压成分，但绝不能替代降压药物",
    redFlagEn: "Celery contains some blood pressure-lowering components, but absolutely cannot replace medication.",
    elderZh: "芹菜对身体好，但不能代替降压药。该吃药还得吃药。",
    elderEn: "Celery is good for health but cannot replace blood pressure medication. Keep taking prescribed medicine.",
    actionZh: "提醒高血压患者遵医嘱服药，不要擅自停药。",
    actionEn: "Remind hypertensive patients to take medicine as prescribed and not stop on their own.",
    summaryZh: "芹菜降压不能替代药物，擅自停药可能危及生命。",
    summaryEn: "Celery lowering blood pressure cannot replace medication; stopping medicine may endanger life.",
  },
  {
    id: "leek-aphrodisiac",
    patterns: [/韭菜.*壮阳/, /韭菜.*男人.*多吃/],
    score: 45,
    verdict: "suspicious",
    redFlagZh: "韭菜没有特殊的壮阳功效，属于普通蔬菜",
    redFlagEn: "Leeks have no special aphrodisiac effects; they are ordinary vegetables.",
    elderZh: "韭菜就是普通的菜，没有特别的功效。别信那些说法。",
    elderEn: "Leeks are just ordinary vegetables with no special effects. Don't believe those claims.",
    actionZh: "提醒老人理性看待食物功效，不要迷信食疗。",
    actionEn: "Remind the elder to view food effects rationally and not believe in food therapy myths.",
    summaryZh: "韭菜壮阳功效被夸大，属于没有科学依据的说法。",
    summaryEn: "Leek aphrodisiac effects are exaggerated; claims without scientific basis.",
  },
  {
    id: "instant-noodle-detox",
    patterns: [/方便面.*排毒.*一个月/, /方便面.*垃圾.*食品/],
    score: 45,
    verdict: "suspicious",
    redFlagZh: "方便面是安全食品，不存在需要排毒的情况，只是营养不够全面",
    redFlagEn: "Instant noodles are safe food; there's no need for detox, just incomplete nutrition.",
    elderZh: "方便面偶尔吃没问题，不会中毒。就是营养少点，别天天吃。",
    elderEn: "Instant noodles are fine occasionally; they won't poison you. Just low in nutrition; don't eat daily.",
    actionZh: "建议老人均衡饮食，方便面可作为应急食品偶尔食用。",
    actionEn: "Suggest the elder maintain a balanced diet; instant noodles can be eaten occasionally as emergency food.",
    summaryZh: "方便面排毒论是夸大其词，方便面是安全的加工食品。",
    summaryEn: "Instant noodle detox claims are exaggerations; they are safe processed food.",
  },
  {
    id: "white-hair-pluck",
    patterns: [/白头发.*拔.*长/, /白头发.*拔一根.*长/],
    score: 50,
    verdict: "suspicious",
    redFlagZh: "拔白头发不会影响其他头发变白，但可能损伤毛囊",
    redFlagEn: "Plucking white hair won't affect other hairs turning white, but may damage hair follicles.",
    elderZh: "拔白头发不会让别的头发变白，但拔多了可能伤头皮。",
    elderEn: "Plucking white hair won't make others turn white, but too much plucking may hurt the scalp.",
    actionZh: "建议老人不要频繁拔白头发，可通过染发或接受自然老化。",
    actionEn: "Suggest the elder not pluck white hair frequently; use hair dye or accept natural aging.",
    summaryZh: "拔白头发长三根是民间说法，没有科学依据。",
    summaryEn: "Plucking one white hair grows three is a folk saying with no scientific basis.",
  },
  {
    id: "tea-sober",
    patterns: [/喝茶.*解酒/, /喝醉.*喝茶/],
    score: 45,
    verdict: "suspicious",
    redFlagZh: "茶不能解酒，反而可能加重心脏负担",
    redFlagEn: "Tea cannot sober you up; it may increase heart burden instead.",
    elderZh: "喝茶解不了酒，喝多了茶心跳还快。喝醉了多喝水休息。",
    elderEn: "Tea doesn't sober you up; too much tea speeds up heartbeat. Drink water and rest when drunk.",
    actionZh: "提醒老人不要试图用茶解酒，醉酒应多喝水休息。",
    actionEn: "Remind the elder not to use tea to sober up; drink water and rest when drunk.",
    summaryZh: "喝茶解酒是错误的认知，茶不能加速酒精代谢。",
    summaryEn: "Tea sobering up is a misconception; tea cannot accelerate alcohol metabolism.",
  },
  {
    id: "crab-persimmon",
    patterns: [/螃蟹.*柿子.*中毒/, /螃蟹.*柿子.*一起.*吃/],
    score: 45,
    verdict: "suspicious",
    redFlagZh: "螃蟹和柿子同食不会中毒，食物相克理论没有科学依据",
    redFlagEn: "Eating crabs and persimmons together won't cause poisoning; food incompatibility theory has no scientific basis.",
    elderZh: "螃蟹和柿子一起吃不会中毒，放心吃。就是别吃太多凉的。",
    elderEn: "Eating crabs and persimmons together won't poison you; don't worry. Just don't eat too much cold food.",
    actionZh: "告诉老人食物相克理论已被科学否定。",
    actionEn: "Tell the elder that food incompatibility theory has been scientifically debunked.",
    summaryZh: "食物相克论是已被否定的伪科学，螃蟹柿子同食无害。",
    summaryEn: "Food incompatibility theory is debunked pseudoscience; crabs and persimmons are safe together.",
  },
  {
    id: "glasses-worsen",
    patterns: [/戴眼镜.*近视.*深/, /眼镜.*度数.*增加/],
    score: 45,
    verdict: "suspicious",
    redFlagZh: "戴眼镜不会导致近视加深，不戴眼镜反而可能加重眼疲劳",
    redFlagEn: "Wearing glasses doesn't worsen myopia; not wearing them may increase eye strain.",
    elderZh: "戴眼镜不会让眼睛更近视。该戴就戴，别省这个钱。",
    elderEn: "Glasses don't make eyes more nearsighted. Wear them when needed; don't skimp on this.",
    actionZh: "建议老人定期检查视力，按医嘱佩戴合适的眼镜。",
    actionEn: "Suggest the elder have regular vision checks and wear suitable glasses as prescribed.",
    summaryZh: "戴眼镜加深近视是错误的说法，属于常见的视力误区。",
    summaryEn: "Glasses worsening myopia is a false claim; common vision misconception.",
  },
  {
    id: "lard-better",
    patterns: [/猪油.*植物油.*健康/, /猪油.*天然.*健康/],
    score: 45,
    verdict: "suspicious",
    redFlagZh: "猪油饱和脂肪酸含量高，过量摄入增加心血管疾病风险",
    redFlagEn: "Lard is high in saturated fat; excessive intake increases cardiovascular disease risk.",
    elderZh: "猪油香但吃多了对血管不好。植物油和猪油换着吃，别只吃一种。",
    elderEn: "Lard is tasty but bad for blood vessels in excess. Alternate between vegetable oil and lard.",
    actionZh: "建议老人控制猪油摄入，以植物油为主。",
    actionEn: "Suggest the elder limit lard intake and mainly use vegetable oil.",
    summaryZh: "猪油比植物油更健康的说法是错误的，猪油应适量食用。",
    summaryEn: "Claims that lard is healthier than vegetable oil are false; lard should be eaten in moderation.",
  },
  {
    id: "soy-milk-empty",
    patterns: [/豆浆.*空腹.*拉肚子/, /豆浆.*不能.*空腹/],
    score: 50,
    verdict: "suspicious",
    redFlagZh: "空腹喝豆浆不会导致腹泻，豆浆是安全的早餐饮品",
    redFlagEn: "Drinking soy milk on an empty stomach won't cause diarrhea; it's a safe breakfast beverage.",
    elderZh: "空腹喝豆浆没问题，不会拉肚子。豆浆是好东西。",
    elderEn: "Drinking soy milk on an empty stomach is fine; it won't cause diarrhea. Soy milk is good.",
    actionZh: "告诉老人豆浆可以空腹饮用，是营养丰富的饮品。",
    actionEn: "Tell the elder that soy milk can be drunk on an empty stomach; it's a nutritious beverage.",
    summaryZh: "空腹不能喝豆浆是错误的说法，豆浆是安全的营养饮品。",
    summaryEn: "Not drinking soy milk on an empty stomach is false; it's a safe, nutritious beverage.",
  },
  {
    id: "reboiled-water",
    patterns: [/反复.*烧开.*致癌/, /千滚水.*致癌/, /多次.*烧开.*亚硝酸盐/],
    score: 45,
    verdict: "suspicious",
    redFlagZh: "反复烧开的水亚硝酸盐含量极低，不会致癌",
    redFlagEn: "Reboiled water contains extremely low nitrite levels and does not cause cancer.",
    elderZh: "水烧开了再烧几次不会致癌，放心喝。",
    elderEn: "Reboiling water a few times won't cause cancer; drink with confidence.",
    actionZh: "告诉老人千滚水致癌是谣言，反复烧开的水是安全的。",
    actionEn: "Tell the elder that reboiled water causing cancer is a rumor; reboiled water is safe.",
    summaryZh: "千滚水致癌是已被辟谣的谣言，反复烧开的水安全可饮。",
    summaryEn: "Reboiled water causing cancer is a debunked rumor; reboiled water is safe to drink.",
  },
];

// 合并所有规则（按优先级：scam < health < misinformation < safe）
const rules: Rule[] = [
  ...SCAM_RULES,
  ...HEALTH_RULES,
  ...EXAGGERATED_RULES,
  ...SAFE_RULES,
];

// 分类统计
const STATS = {
  scam: SCAM_RULES.length,
  health: HEALTH_RULES.length,
  exaggerated: EXAGGERATED_RULES.length,
  safe: SAFE_RULES.length,
  total: rules.length,
};

export class RuleBasedProvider implements Provider {
  name = "rule-based";

  async chat(messages: ChatMessage[], _signal?: AbortSignal, _options?: { enableSearch?: boolean }): Promise<string> {
    const userContent = messages.find((m) => m.role === "user")?.content || "";
    const content = userContent.replace(/---/g, "").trim();

    // 优先查询本地辟谣知识库 - 直接匹配（阈值0.7）
    const directMatch = hasDirectMatch(content);
    if (directMatch.matched && directMatch.entry) {
      const e = directMatch.entry;
      // 从truth中提取与当前claim最相关的段落（合集文章可能包含多条谣言）
      const truthParagraph = extractRelevantTruth(e.truth, e.claim);
      const truth = truthParagraph.length > 150 ? truthParagraph.slice(0, 150) + "..." : truthParagraph;
      return JSON.stringify({
        credibilityScore: 15,
        verdict: "misinformation",
        redFlags: [
          {
            zh: `该内容已被官方辟谣平台证伪：${e.claim.slice(0, 60)}`,
            en: `Debunked by official rumor-cracking platform: ${e.claim.slice(0, 60)}`,
          },
        ],
        elderExplanation: {
          zh: `这是假的。${truth}`,
          en: `This is false. ${truth}`,
        },
        actionSuggestion: {
          zh: `该辟谣来源：${e.source} (${e.publishDate})，建议转发给家人阅读官方辟谣。`,
          en: `Source: ${e.source} (${e.publishDate}). Share the official debunking with family.`,
        },
        summary: {
          zh: `该内容已被官方辟谣平台证伪：${e.claim.slice(0, 80)}。`,
          en: `Officially debunked: ${e.claim.slice(0, 80)}.`,
        },
      });
    }

    // 知识库模糊匹配 - 阈值0.5
    const fuzzyMatches = searchPiyao(content, 1);
    if (fuzzyMatches.length > 0) {
      const e = fuzzyMatches[0];
      const truthParagraph = extractRelevantTruth(e.truth, content);
      const truth = truthParagraph.length > 150 ? truthParagraph.slice(0, 150) + "..." : truthParagraph;
      return JSON.stringify({
        credibilityScore: 25,
        verdict: "misinformation",
        redFlags: [
          {
            zh: `知识库匹配到相关辟谣记录：${e.claim.slice(0, 60)}`,
            en: `Knowledge base matched related debunking record: ${e.claim.slice(0, 60)}`,
          },
        ],
        elderExplanation: {
          zh: `这可能是假的。${truth}`,
          en: `This may be false. ${truth}`,
        },
        actionSuggestion: {
          zh: `该辟谣来源：${e.source} (${e.publishDate})，建议核实后再行动。`,
          en: `Source: ${e.source} (${e.publishDate}). Verify before taking action.`,
        },
        summary: {
          zh: `知识库匹配到相关记录，该内容可能为虚假信息：${e.claim.slice(0, 80)}。`,
          en: `Knowledge base matched related record; this content may be misinformation: ${e.claim.slice(0, 80)}.`,
        },
      });
    }

    // 知识库无直接匹配，继续硬编码规则匹配
    const matchedRules = rules.filter((rule) =>
      rule.patterns.some((p) => p.test(content))
    );

    if (matchedRules.length === 0) {
      return JSON.stringify({
        credibilityScore: 70,
        verdict: "needs-verification",
        redFlags: [
          {
            zh: "未匹配到已知模式，该内容无法通过本地规则库判断",
            en: "No known pattern matched; content cannot be judged by the local rule base.",
          },
        ],
        elderExplanation: {
          zh: "这条消息我不太确定真假。咱们先不急着转发，可以再查查。",
          en: "I'm not sure if this message is true. Let's not rush to forward it; we can verify it further.",
        },
        actionSuggestion: {
          zh: "建议通过权威媒体核实，或配置AI模型进行深入分析。",
          en: "Verify through authoritative media, or configure an AI model for deeper analysis.",
        },
        summary: {
          zh: "内容未触发本地规则库中的已知模式，建议谨慎对待。",
          en: "Content did not trigger known patterns in the local rule base; treat with caution.",
        },
      });
    }

    // 取最低分（最危险的）作为最终评分
    const finalScore = Math.min(...matchedRules.map((r) => r.score));
    const primaryRule = matchedRules.find((r) => r.score === finalScore) || matchedRules[0];

    const redFlags = matchedRules.map((r) => ({
      zh: r.redFlagZh,
      en: r.redFlagEn,
    }));

    return JSON.stringify({
      credibilityScore: finalScore,
      verdict: primaryRule.verdict,
      redFlags,
      elderExplanation: {
        zh: primaryRule.elderZh,
        en: primaryRule.elderEn,
      },
      actionSuggestion: {
        zh: primaryRule.actionZh,
        en: primaryRule.actionEn,
      },
      summary: {
        zh: primaryRule.summaryZh,
        en: primaryRule.summaryEn,
      },
    });
  }

  async healthCheck(): Promise<boolean> {
    return true;
  }
}

export { STATS };
